<?php
return [
    1  => "Gulmira Kozhamkulova",
    2  => "Bauyrzhan Bekbolatov",
    3  => "Daulet Torekhanov",
    4  => "Araneta Myrna",
    5  => "Wongdhu Gyalpo",
    6  => "Maiah Lintag",
    7  => "Azat Mazkenov",
    8  => "Nodira Samandarova",
    9  => "Ilyas Sarsenbayev",
    10 => "Muslima Turdaliyeva",
    11 => "Rano Sharapova",
    12 => "Azam Avazov",
    13 => "Dinara Kozhakhmetova",
    14 => "Faniya Askarova",
    15 => "Mahmoud Abdallah",
    16 => "Javlonbek Rustamjonov",
    17 => "Kamol Mukhsitdinov",
    18 => "Sarah Louise Thompson",
    19 => "Lily Maryati Tjakradipura",
    20 => "Bhavesh Singh Chandradev",
    21 => "Yerkin Shantayev",
    22 => "Ilias Zhanabayev",
    23 => "Oguz Korkmaz",
    24 => "Akbota Sultanbekova",
    25 => "Anatoliy Kuznetsov",
    26 => "Elnur Nazaraliyev",
    27 => "Adelina",
    28 => "Anil"
];
